# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
