# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseorder_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='posted',
            new_name='post_items',
        ),
    ]
