# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20161104_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
