# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseorder_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='post_status',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='posting_status',
            field=models.BooleanField(default=False),
        ),
    ]
