# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_auto_20161109_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['post_items', 'purchase_date']},
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='posting_status',
            new_name='posted',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rs.', max_digits=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rs.', max_digits=100),
        ),
    ]
