# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161105_0807'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('linetotal', models.DecimalField(decimal_places=2, help_text='Rs.', max_digits=100)),
                ('quantity_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('posting_status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_line_items', to='products.Product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_line_items', to='sales.Sale')),
            ],
        ),
    ]
