# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['customer']},
        ),
    ]
