# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20161116_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
    ]
