# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20161117_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelineitem',
            name='free_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='stale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
