# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_sale_post_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='post_items',
            field=models.BooleanField(default=False),
        ),
    ]
