# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_sale_post_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelineitem',
            name='linetotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rs.', max_digits=100),
        ),
    ]
