# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField(default=0, help_text='gram')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('active', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], max_length=1)),
            ],
        ),
    ]
