# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161104_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rs.', max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_unit',
            field=models.PositiveIntegerField(default=0, help_text='No.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rs.', max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_stock',
            field=models.IntegerField(default=0, help_text='No.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='gram'),
        ),
    ]
